# model
mlps: [16, 64]
ks: [64, 64]
radius: [0.15, 0.2]
thre: 0.05
nsample: 1024
min_cluster_size: 72
rotations: 8

# dataset
batch_size: 1
num_workers: 16

# optim
learning_rate: 0.001

# seed
seed: 3407


# dataset
shapenet_root: './dataset/ShapeNetCore.v2/'
split_root: './data_split'
eval_root: './dataset/test'
npoints: 512
mvp_root: './dataset'
cat: 'all'

# pretrained weights
weights: pretrained/model.pth
